#ifndef MAIN_BOARD_PINOUT_H
#define MAIN_BOARD_PINOUT_H
#include <Wire.h>
#include <SPI.h>

#define VERSION_MAIN_BOARD_PINOUT_H "REV: X0"

#define MAIN_BOARD_MOSI 11
#define MAIN_BOARD_MISO 13
#define MAIN_BOARD_SCK 12
#define MAIN_BOARD_SPI_FREQ 80000000
#define MAIN_BOARD_SD_SPEED SD_SCK_MHZ(30)

#define MAIN_BOARD_ETHERNET_CS 2
#define MAIN_BOARD_SD_CS 10
#define MAIN_BOARD_LCD_1_CS 5
#define MAIN_BOARD_LCD_2_CS 6
#define MAIN_BOARD_LCD_RESET 4
#define MAIN_BOARD_LCD_DC 21


#define MAIN_BOARD_WS2812_PIN 40


#define MAIN_BOARD_SERVO_1_PIN 19
#define MAIN_BOARD_SERVO_2_PIN 20
#define MAIN_BOARD_SERVO_3_PIN 39
#define MAIN_BOARD_SERVO_4_PIN 38


#define MAIN_BOARD_ROTARY_ENCODER_A 47
#define MAIN_BOARD_ROTARY_ENCODER_B 48
#define MAIN_BOARD_ROTARY_ENCODER_SW 14


#define MAIN_BOARD_UART_0_CTS 16
#define MAIN_BOARD_UART_0_RTS 15

#define MAIN_BOARD_UART_1_TX 17
#define MAIN_BOARD_UART_1_RX 18

#define MAIN_BOARD_UART_1_BAUD_RATE 115200


#define MAIN_BOARD_I2C_SDA 3
#define MAIN_BOARD_I2C_SCL 9


#define MAIN_BOARD_SPKR 7


#define MAIN_BOARD_ANALOG_MUX_IN 1


#define NUM_DIGITAL_IO_EXPANDERS 4
#define MAIN_BOARD_DIGITAL_IO_EXPANDER_BASE_ADDR 0x21


#define MAIN_BOARD_I2C_MUX_ADDR 0x70

#endif